name: 'Coverage monitor'
description: 'A GitHub Action that monitor coverage.'
branding:
  icon: "check"
  color: "green"
inputs:
  github_token:
    description: "**Required.** The GITHUB_TOKEN secret."
    required: true
  coverage_path:
    description: "**Required.** Path to coverage reports."
    required: false
  coverage_format:
    description: |
      Format of coverage, supported: `auto`, `clover` and `json-summary`.
      If not set the action will try to guess the format, by file extension, name and eventually by content.
    required: false
    default: 'auto'
  clover_file:
    description: |
      **Deprecated.** Path to Clover XML file. This option is deprecated, replaced with `coverage_path`.
      If both `clover_file` and `coverage_path` are set, the action will fail.
    required: false
    deprecationMessage: 'Use `coverage_path` instead'
  working_dir:
    description: "The working directory of the action. Defaults to workflow workspace."
    required: false
    default: ''
  threshold_alert:
    description: "Mark the build as unstable when coverage is less than this threshold."
    required: false
    default: '50'
  threshold_warning:
    description: "Warning when coverage is less than this threshold."
    required: false
    default: '90'
  threshold_metric:
    description: "A metric to check threshold on, supported: `statements`, `lines`, `methods` or `branches`."
    required: false
    default: 'lines'
  check:
    description: "Whether check the coverage thresholds."
    required: false
    default: 'true'
  status_context:
    description: "A string label to differentiate this status from the status of other systems."
    required: false
    default: 'Coverage Report'
  comment:
    description: "Whether comment the coverage report."
    required: false
    default: 'true'
  comment_context:
    description: "A string label to differentiate the comment posted by this action."
    required: false
    default: 'Coverage Report'
  comment_mode:
    description: "A mode for comments, supported: `replace`, `update` or `insert`."
    required: false
    default: 'replace'
  comment_footer:
    description: "Whether comment may contain footer."
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
